### ISSUE TITLE
Duplicate phrases in ranked list

### ISSUE THREAD

**Issue by haroldpadilla** [andrewrosss/rake-spacy#12]
I'm seeing phrases getting duplicated quite often. When I compare to rake-nltk, the phrases are only shown once. I made two sample scripts (one with rake-ntlk and one with rake-spacy):

rake-nltk:
```python
from rake_nltk import Rake

# Uses stopwords for english from NLTK, and all puntuation characters.
r = Rake()

r.extract_keywords_from_text(
    """diary for my best friend. My diary is the best. Then again, I really love this diary. I also happen with this phrase: natural language processing. Let's type the natural language processing again.""")

print(r.get_ranked_phrases_with_scores())
```

Result:
```python
[(9.0, 'natural language processing'), (4.0, 'really love'), (4.0, 'also happen'), (3.5, 'best friend'), (1.5, 'best'), (1.0, 'type'), (1.0, 'phrase'), (1.0, 'let'), (1.0, 'diary')]
```

rake-spacy:
```python
from rake_spacy import Rake

r = Rake()

ranklist = r.apply(
    """diary for my best friend. My diary is the best. Then again, I really love this diary. I also happen with this phrase: natural language processing. Let's type the natural language processing again.""")

print(ranklist)
```

Result:
```python
[(6.0, natural language processing), (6.0, natural language processing), (3.0, best friend), (3.0, diary), (3.0, diary), (3.0, diary), (2.0, best), (1.0, Let), (1.0, happen), (1.0, love), (1.0, phrase), (1.0, type)]
```

In this case, the phrases that appears twice (in rake-spacy) in the list with ranked phrases are `diary` and `natural language processing`. Is there a way to remove the duplicated keywords/phrases from the results? I'm not sure if RAKE has any provisions for duplications like this.

**Comment by andrewrosss** [comment]
At the moment there isn't any configuration to directly handle de-duplicating the results. 

After, skimming the original RAKE paper it doesn't look like there's any explicit mention of a deduping process as the co-occurance graph is just a means to score (and rank) candidate phases, but deduping may be implied based on the example they provide:

<img width="400" alt="Screen Shot 2021-03-10 at 4 10 51 PM" src="https://user-images.githubusercontent.com/23389447/110698286-75ca6d00-81bb-11eb-9ff5-711e049720e1.png">

As a minimal workaround you could do something like:

```python
from rake_spacy import Rake

def dedup(ranklist):
    return list({p.text: (s, p) for s, p in ranklist}.values())

r = Rake()

ranklist = r.apply(
    """diary for my best friend. My diary is the best. Then again, I really love this diary. I also happen with this phrase: natural language processing. Let's type the natural language processing again.""")
ranklist = dedup(ranklist)

print(ranklist)
```

But, perhaps deduping the results is the correct default behavior.

**Comment by andrewrosss** [comment]
One thing to consider as well is that the phrases/keywords that are extracted by `rake-spacy` are "richer" than just plain substrings extracted from the text.

The returned ranklist is composed of pairs where the first entry is the phrase's score, but the second entry is a spacy `Span` (hence the lack of single quotes in the output from the sample you provided), which carries with it additional metadata, for example it carries positional information about where it was located in the parent document.

So depending on the application "deduplicating", at least as described in the previous comment, may or may not be the right thing to want to do. If you just need the strings then it probably makes sense, but if you value having the `Span` objects then maybe not.

**Comment by haroldpadilla** [comment]
> One thing to consider as well is that the phrases/keywords that are extracted by `rake-spacy` are "richer" than just plain substrings extracted from the text.
> 
> The returned ranklist is composed of pairs where the first entry is the phrase's score, but the second entry is a spacy `Span` (hence the lack of single quotes in the output from the sample you provided), which carries with it additional metadata, for example it carries positional information about where it was located in the parent document.
> 
> So depending on the application "deduplicating", at least as described in the previous comment, may or may not be the right thing to want to do. If you just need the strings then it probably makes sense, but if you value having the `Span` objects then maybe not.

Totally agree on the importance of keeping both options available. Also, thanks for the dedup function; it does the trick.
